### PR TITLE
fix: Trust the filesystem to move files

### LINKED ISSUE #155: [BUG] cacache doesn't work on Android
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
~ $ npm install yarn
npm ERR! code EACCES
npm ERR! syscall link
npm ERR! path /data/data/com.termux/files/home/.npm/_cacache/tmp/14de33dd
npm ERR! dest /data/data/com.termux/files/home/.npm/_cacache/content-v2/sha512/d1/d2/d481d770644c0c5e31275a2b952a18da6097da58f146549fb26a5f5d8ac389ffcd10db5d924df1176590499cd2d92b5c21f948efab003774723c809d2d6c
npm ERR! errno EACCES
npm ERR!
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR!
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 10427:10427 "/data/data/com.termux/files/home/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-11-21T01_31_59_253Z-debug-0.log
```

### Expected Behavior

NPM install package successfully.

### Steps To Reproduce

In Termux, run
```
apt update && apt upgrade 
apt install nodejs-lts
npm install -g npm@9.1.2
npm install yarn
```
Then error message will occur.

`fs.link` will try to use hard link, which is disallowed by seccomp in Android. The maintainer of termux packages have applied a patch to solve this, but when users update `cacache` or `npm`, the patch will not work anymore.

Related issues: termux/termux-packages#11293, termux/termux-packages#13293
Possible patch: https://github.com/termux/termux-packages/blob/master/packages/nodejs/deps-npm-node_modules-cacache-lib-util-move-file.js.patch

### Environment

- npm: 9.1.2
- Node: 16.18.1
- OS: Android
- platform: Termux 0.118

### PR DESCRIPTION
**Pull request by wraithgar**
The original lib/util/move-file.js has gone through many iterations over
the last several years.  It no longer represents anything close to the
original intent.

Most of the functionality it was originally trying to work around is now
something that `@npmcli/fs#moveFile` does, and better.  Trying to move a
file by creating a hard link and unlinking the old file is an
optimization best left to the operating system when you ask it to move a
file.  In fact the `@npmcli/fs#moveFile` method tries a *rename* first,
which is the best choice all around.  It also supports an "overwrite:
false" flag so we can still error out if the destination already exists.

This PR removes all of the old legacy code.

Closes #155

### CODE REVIEW

File: lib/content/write.js [hunk 1]
```diff
@@ -161,8 +161,14 @@ async function moveToDestination (tmp, cache, sri, opts) {
...
 
   await fs.mkdir(destDir, { recursive: true })
-  await moveFile(tmp.target, destination)
-  tmp.moved = true
+  try {
+    await moveFile(tmp.target, destination, { overwrite: false })
+    tmp.moved = true
+  } catch (err) {
+    if (!err.message.startsWith('The destination file exists')) {
+      throw Object.assign(err, { CODE: 'EEXIST' })
```
Comment (nlf) [inline lib/content/write.js:169]:
```suggestion
      throw Object.assign(err, { code: 'EEXIST' })
```

**Review by nlf — CHANGES_REQUESTED** [review]

**Review by nlf — APPROVED** [review]
