### PR TITLE
fix: attach a catch handler to the handleContentP promise

### LINKED ISSUE #249: [BUG] put.stream can crash the process with unhandled exception, even when error handler is attached
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Process terminates with error:
```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EACCES: permission denied, open 'tmp/3164ed41'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: 'tmp/3164ed41'
}
```

### Expected Behavior

Process does not terminate and the stream error handler is called

### Steps To Reproduce

Run the following script. It will change the `tmp` folder permission, so that an error is triggered. It can happen in other circumstances too (of of disk space, etc.)
In certain cases this results in a lingering rejected promise `handleContentP` within `lib/content/write.js`
In the example, such case is when the readable stream has not ended.

```js
const {Readable} = require('stream');
const {chmod} = require('fs/promises');
const {existsSync} = require('fs');
const cacache = require('cacache');

const read = (...params) => new Readable({
    read(size) {
        if (params.length) this.push(params.shift());
    }
});

require('http').createServer().listen(() => console.log('listening'));

((async()=>{
    if (existsSync('./tmp')) await chmod('./tmp', 0777);
    await cacache .put('.', 'key1', '1')
    await chmod('./tmp', 0555);
    return read('2').pipe(cacache.put.stream('.', 'key2')).on('error', console.error);

})()).catch(console.error);
```

### Environment

- Node: v20.9.0
- OS: Linux

### PR DESCRIPTION
**Pull request by kalinkrustev**
This attaches a catch handler to the handleContentP promise, as in some cases the flush is not called before node decides that this is an unhandled promise rejection.

Fixes #249

### CODE REVIEW

**Comment by wraithgar** [comment]
Ah good catch.  It looks like the thing that is throwing is

https://github.com/npm/cacache/blob/2e1383d1e399211e3bb5bc1363fde2535bd78782/lib/content/write.js#L103

If that were to be brought inside the try/catch block, and then this line

https://github.com/npm/cacache/blob/2e1383d1e399211e3bb5bc1363fde2535bd78782/lib/content/write.js#L114

Changed to

```js
if (!tmp?.moved) {
```

We wouldn't need the catch.

**Comment by wraithgar** [comment]
There is an error handler set up on the promise at

https://github.com/npm/cacache/blob/2e1383d1e399211e3bb5bc1363fde2535bd78782/lib/content/write.js#L92

But it only happens during flush, way too late.

File: lib/content/write.js [hunk 1]
```diff
@@ -67,6 +67,7 @@ class CacacheWriteStream extends Flush {
         this.cache,
         this.opts
       )
+      this.handleContentP.catch(error => this.destroy(error))
```
Comment (wraithgar) [inline lib/content/write.js:70]: `this.destroy` seems to be overreaching in scope.  I think we want `cb(error)`

We can also attach it directly to the function call `handleContent().catch()`

Comment (kalinkrustev) [reply lib/content/write.js:70]: Unfortunately this does not help.

**Comment by kalinkrustev** [comment]
> We wouldn't need the catch.

Why? It will still be a rejected promise.

**Review by wraithgar — APPROVED** [review]

**Comment by wraithgar** [comment]
Looks good w/ just the simple .catch added.  Were you able to test this against your example in https://github.com/npm/cacache/issues/249?

**Comment by kalinkrustev** [comment]
Yes, I tested it and it works fine.
